DROP TABLE RESERVA;
DROP TABLE SALA;
DROP TABLE USUARIO;

CREATE TABLE USUARIO(
	ID VARCHAR(20) NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDOS VARCHAR(40) NOT NULL,
	DIRECCION VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(40),
	CIUDAD VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY(ID)
);

CREATE TABLE SALA(
	CODIGO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(200),
	PRECIO DECIMAL(6,3) NOT NULL,
	CONSTRAINT PK_SALA PRIMARY KEY(CODIGO)
);

CREATE TABLE RESERVA(
	ID_RESERVA VARCHAR(20) NOT NULL,
	HORA_INICIO DATE NOT NULL,
	HORA_FIN DATE NOT NULL,
	ID_USUARIO VARCHAR(20) NOT NULL,
	CODIGO_SALA VARCHAR(20) NOT NULL,
	HORA_ENTRADA TIMESTAMP,
	HORA_SALIDA TIMESTAMP,
	CONSTRAINT PK_RESERVA PRIMARY KEY(ID_RESERVA),
	CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_RESERVA_SALA FOREIGN KEY(CODIGO_SALA) REFERENCES SALA(CODIGO)
);