--CREACION USUARIOS
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('00000000','ADMIN','ADMIN','ADMIN','','ADMIN','ADMIN','0', false, null);
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('76454395G','Pedro','Arguelles','C/Comandante Janari','','Oviedo','1234', '25', false, null);
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('76434395A','Paco','Riesgo','C/Comandante Janari','','Oviedo','1234', '25', false, null);
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('76455695F','Saul','Garcia','C/Comandante Janari','','Oviedo','1234', '25',true, '2016-11-01 00:00:00');
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('76432955H','Alfredo','Miravalles','C/Comandante Janari','','Oviedo','1234', '25', true, '2017-1-01 00:00:00');
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('76458395Y','Martin','Diaz','C/Comandante Janari','','Oviedo','1234', '25', false, null);
INSERT INTO USUARIO(DNI,NOMBRE,APELLIDOS,DIRECCION,EMAIL,CIUDAD,PASSWORD, CUOTA, BAJA, FECHA_BAJA) VALUES('76458885Z','David','MuÃ±iz','C/Comandante Janari','','Oviedo','1234', '25', true, '2016-10-01 00:00:00');
--CREACION SALAS
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Spinning',8.90);
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Tenis 1',7.5);
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Tenis 2',7.5);
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Padel 1',8.0);
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Padel 2',8.0);
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Karate',15.0);
INSERT INTO SALA(DESCRIPCION,PRECIO) VALUES('Boxeo',14.0);
--CREACION MONITORES
INSERT INTO MONITORES(ID_USUARIO) VALUES (4);
INSERT INTO MONITORES(ID_USUARIO) VALUES (3);
--CREACION ACTIVIDADES
INSERT INTO ACTIVIDADES(NOMBRE,DESCRIPCION,NUMERO_PLAZAS,ID_MONITOR) VALUES ('REIKI','Metodos de relajacion para alcanzar la paz espiritual',25,0);
INSERT INTO ACTIVIDADES(NOMBRE,DESCRIPCION,NUMERO_PLAZAS,ID_MONITOR) VALUES ('Natacion','Curso para adultos que quieren mejorar su forma de nadar',25,0);
INSERT INTO ACTIVIDADES(NOMBRE,DESCRIPCION,NUMERO_PLAZAS,ID_MONITOR) VALUES ('Padel','Curso basico de padel',25,1);
INSERT INTO ACTIVIDADES(NOMBRE,DESCRIPCION,NUMERO_PLAZAS,ID_MONITOR) VALUES ('Crossfit','Forma de ponerse en forma de forma rapida y entretenida',25,1);
--CREACION RESERVAS
INSERT INTO RESERVA(HORA_INICIO,HORA_FIN,ID_USUARIO,ID_SALA, ID_ACTIVIDAD) VALUES('2016-11-28 09:00:00','2016-11-28 11:00:00','0','2', NULL);
INSERT INTO RESERVA(HORA_INICIO,HORA_FIN,ID_USUARIO,ID_SALA, ID_ACTIVIDAD) VALUES('2016-11-28 10:00:00','2016-11-28 11:00:00','3','2',NULL );
INSERT INTO RESERVA(HORA_INICIO,HORA_FIN,ID_USUARIO,ID_SALA, ID_ACTIVIDAD) VALUES('2016-11-28 14:00:00','2016-11-28 15:00:00','4','2', NULL);
INSERT INTO RESERVA(HORA_INICIO,HORA_FIN,ID_USUARIO,ID_SALA, ID_ACTIVIDAD) VALUES('2016-11-28 10:00:00','2016-11-28 11:00:00','5','1',0 );
INSERT INTO RESERVA(HORA_INICIO,HORA_FIN,ID_USUARIO,ID_SALA, ID_ACTIVIDAD) VALUES('2016-11-28 09:00:00','2016-11-28 11:00:00','6','4',1 );
--CREACION APUNTADOS
INSERT INTO APUNTADOS_ACTIVIDADES(ID_USUARIO,ID_ACTIVIDAD) VALUES(5,0);
INSERT INTO APUNTADOS_ACTIVIDADES(ID_USUARIO,ID_ACTIVIDAD) VALUES(5,1);
INSERT INTO APUNTADOS_ACTIVIDADES(ID_USUARIO,ID_ACTIVIDAD) VALUES(6,1);
INSERT INTO APUNTADOS_ACTIVIDADES(ID_USUARIO,ID_ACTIVIDAD) VALUES(6,0);
